<html>
	<head>
		<meta charset="utf-8">
		<title>Hello World</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" >
		<script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
		<script src="https://cdn.staticfile.org/vue/2.2.2/vue.min.js"></script>
	</head>
	<body>
		<div id="app" class="container">
			<div class="jumbotron">
			<h1><?php echo $content;?></h1>
			<h4><a href="readme.md">读我教程 readme.md</a></h4>
			<h4><a href="https://www.aiirobo.com/yaf/install/medoo_1.6.1.html">Medoo 1.6.1 API 手册(HTML单文件版本)</a></h4>
			<h4><a href="https://pan.baidu.com/s/1d3CIcgJ-s9XcWd9IecYm-g">下载示例代码包(内含YAF手册CHM文件)</a></h4>
			<div class="table-responsive"><table class="table">
				<tr class="row" v-for="item in rows">
					<td class="col-xs-1"><label class="btn btn-primary">{{item.name}}</label></td>
					<td class="col-xs-1"><label class="btn btn-danger"  v-if="item.role=='administrator'">{{item.role}}</label></td>
					<td class="col-xs-1"><label class="btn btn-danger"  v-if="item.role=='advanced'">{{item.role}}</label></td>
					<td class="col-xs-1"><label class="btn btn-danger"  v-if="item.role=='operator'">{{item.role}}</label></td>
					<td class="col-xs-1"><label class="btn btn-success" v-if="item.role=='agent'">{{item.role}}</label></td>
					<td class="col-xs-1"><label class="btn btn-warning" v-if="item.role=='member'">{{item.role}}</label></td>
					<td class="col-xs-1"><label class="btn btn-info"    v-if="item.role=='guest'">{{item.role}}</label></td>
					<td class="col-xs-1"><label class="btn btn-info">{{item.timestamp}}</label></td>
				</tr>
			</table></div>
			</div>
			<div class="panel">

				<div class="well">
					<p>单选框：</p>
					<input type="radio" value="ABC" name="group" v-model="radio">
					<input type="radio" value="XYZ" name="group" v-model="radio">
					<label for="checkbox">{{ radio }}</label>
				</div>

				<div class="well">
					<p>单个复选框：</p>
					<input type="checkbox" value="true" id="checkbox1" v-model="listA">
					<label for="checkbox1">{{ listA }}</label>
					<input type="checkbox" value="false" id="checkbox2" v-model="listB">
					<label for="checkbox2">{{ listB }}</label>
				</div>

				<div class="well">
					<p>多个复选框：</p>
					<input type="checkbox" id="vue" value="Vue" v-model="checkedNames">
					<label for="vue">vue</label>
					<input type="checkbox" id="bootstrap" value="Bootstrap" v-model="checkedNames">
					<label for="bootstrap">Bootstrap</label>
					<p>选择的值为: {{ checkedNames }}</p>
				</div>

				<div class="well">
					<select v-model="selected" name="strawberry">
					<option value="">单选选择</option>
					<option value="vue">vue</option>
					<option value="bootstrap">bootstrap</option>
					</select>
					<p>选择的是: {{selected}}</p>
				</div>

				<div class="well">
					<select multiple v-model="multiple" name="strawberry">
					<option value="">多选列表</option>
					<option value="vue">vue</option>
					<option value="bootstrap">bootstrap</option>
					</select>
					<p>选择的是: {{multiple}}</p>
				</div>

			</div>
		</div>
		<script>
		new Vue({
			el: '#app',
			data: {
				rows:<?php echo json_encode($rows,JSON_UNESCAPED_UNICODE);?>,
				radio : "XYZ",
				listA : "true",
				listB : "true",
				selected : '',
				multiple : ['vue','bootstrap'],
				checkedNames: []
			}
		})
		</script>
	</body>
</html>

